apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: go-hgptkbnu 
  janus-idp.io/tekton: go-hgptkbnu
  backstage.io/kubernetes-id: go-hgptkbnu
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: go-hgptkbnu
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml